version: '3'
services:
  mysql8:
    container_name: mysql840
    image: mysql:8.4.0
    volumes:
      - /home/<USER>/dockerdata/mysql840:/var/lib/mysql
    restart: no  # on-failure:2
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=SPRING
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    ports:
      - 3306:3306
